version: "2.0"
services:
    gpt:
        build: .
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.gpt.rule=Host(`gp.ridho.dev`)"
            - "traefik.http.routers.gpt.entrypoints=websecure"
            - "traefik.http.routers.gpt.tls.certresolver=myresolver"
            - "traefik.docker.network=global"
        env_file:
            - prod.env
        networks:
            global:
                aliases:
                    - gpt
        volumes:
            - ./data:/app/data

networks:
    global:
        external: true
